### ISSUE TITLE
How to use at request time

### ISSUE THREAD

**Issue by mcintyre321** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#10]
I'd like to dynamically create a certificate at request-time - I'm trying to write a reverse proxy that won't know the host until runtime. Is there a way to do this then, instead of on-startup?

**Comment by killswtch** [comment]
Certificate generation is resource-consuming and slow. You would very quickly encounter rate limits if you attempted this. Also, this library isn't structured in a way that would make this feasible.

**Comment by mcintyre321** [comment]
Thanks for the reply. I wasn't imagining creating millions of new certs, just every so often, when a client adds a new domain.

**Comment by killswtch** [comment]
Can your application be notified when a client adds a domain? You could trigger an application restart (something along the lines of https://edi.wang/post/2019/3/7/restart-an-aspnet-core-application-programmatically) when a new domain is added, with the new list of domains included in Startup.
