### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AydinE** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#19]
warn: FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService[0]
          Exception occured renewing certificates: 'Object reference not set to an instance of an object..'
          System.NullReferenceException: Object reference not set to an instance of an object.

I just tried adding this to my project, I followed the instruction and looked at the sample but the error above shows up. Any idea what I did wrong?

**Comment by srudin** [comment]
Please also see https://github.com/ffMathy/FluffySpoon.AspNet.LetsEncrypt/issues/18 which was closed although it is NOT solved.

**Comment by ffMathy** [comment]
More debugging has been added in 1.0.128. Can you try that version?
