### ISSUE TITLE
ASP.NET Core 3.0 LetsEncryptChallengeApprovalMiddleware not processing

### ISSUE THREAD

**Issue by YetaWF** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#28]
First off, let me thank you for this awesome library that made my life just so much easier.
I am using it with ASP.NET Core 3.0,  v1.137.0  (cloned repo) and v1.111.0 (nuget).
I found that with neither version, the LetsEncryptChallengeApprovalMiddleware would ever be processed. It would be called but passed the request on next.

It looks like 
if (context.Request.Path.StartsWithSegments(MagicPrefix))
is causing the issue, because MagicPrefix has an ending slash, which results in the expression evaluating to false (see watch window below). By removing the trailing slash it evaluates correctly.
MagicPrefix is used elsewhere where a slash MUST be present.

![image](https://user-images.githubusercontent.com/14954337/71040301-4d58dd80-20f4-11ea-807f-a516887232b0.png)

I found some issues where others ran into this problem, like https://github.com/aspnet/AspNetCore/issues/2713

For now I just made a MagicPrefixWithoutSlash variable in LetsEncryptChallengeApprovalMiddleware for

if (context.Request.Path.StartsWithSegments(MagicPrefixWithoutSlash))

in InvokeAsync.
And everything now magically works.

Again, 1000 thanks for your awesome library.

**Comment by ffMathy** [comment]
Wow thank you for the awesome donation and your kind words!

Could you open a PR with this change? ♥️

**Comment by YetaWF** [comment]
All is well as I now switched to the new nuget package.
Thanks!
