### ISSUE TITLE
Would a PR to increase/improve logging be accepted?

### ISSUE THREAD

**Issue by willdean** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#72]
We're currently trying to debug a problem with using LE with Azure App Services, and it would really help to have some more detailed logging on what is happening.

As an example, we're seeing `The given challenge did not match /.well-known/acme-challenge/xxxx among []` - even though we have the challenge memory persistence enabled.   It would be handy if we could see challenges being added to and removed from the memory persistence in more detail than is currently possible.

Would you consider taking a PR which substantially increased the logging (at the Debug level, I'd assume) in various bits of the project?

**Comment by ffMathy** [comment]
Definitely! But consider Trace for the more noisy ones.

**Comment by willdean** [comment]
Thanks - I won't make it much more chatty.

The horrors of trying to use `ILogger<T>` in code where you can't easily inject it are probably going to rather limit my ambitions here anyway, but I'll see if I can add enough logging to at least get to the bottom of our current problem...
