### ISSUE TITLE
Azure will not let certificates be updated if they're in use

### ISSUE THREAD

**Issue by willdean** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#73]
We're seeing a failure to update our Azure App Service certificate - the message from FluffySpoon which gets logged by our application is:

>  Exception occured renewing certificates: 'Operation returned an invalid status code 'Conflict'.'

This is thrown by `CertificatesOperationsExtensions.UpdateAsync` called by `PersistAsync` in the Azure certificate persistence strategy.

In the Azure portal, you can see an associated activity log error:

> Cannot remove certificate with thumbprint XXXX because it is used for hostname <our domain>.

It appears that although it might once have been possible to call UpdateAsync to replace a cert which was currently bound, this is no longer possible.

My guess is that the general solution to this is to:

1. Upload a new certificate with a new name
2. Change the binding to point to the new certificate
3. Remove the old certificate

I'm quite happy to implement this if it sounds like it would be useful, but I'm not quite sure why nobody else is having this problem, so perhaps I'm missing something.   This is a problem which has prevented our main app renewing for the last couple of months (which is as long as it's been using FluffySpoon), and I've just repro'd it on a deployment slot.

There are some other slot-related problems I may file other issues on, but this doesn't seem to be slot-related, as we're seeing it on 'non-slot' apps too.

**Comment by ffMathy** [comment]
PRs are very welcome, since I don't have much time myself lately, and no Azure account to test on.

**Comment by willdean** [comment]
Well, I have until the 31st March (when is when our production LE cert that is failing to renew expires) to get the renewal working...

I think the Azure stuff is a bit of a minority interest now that you can get free certs from MS, but they don't work for naked domains like we're using, so we'd still like it to work.

I will file some PRs (sorry, I know PRs represent a lot of work for maintainers)
