### ISSUE TITLE
Azure deployment slot support

### ISSUE THREAD

**Issue by willdean** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#74]
I have been investigating some Azure issues using a deployment slot (the staging slot of our production application) which has thrown up some issues with the current slot support:
(Almost all the code I'm discussing is in `AzureAppServiceSslBindingCertificatePersistenceStrategy.PersistAsync`)

1. By default, FS will not find apps in deployment slots when trying to find the app which matches a domain at the start of the persisting process.
2. There is a string property in AzureOptions called "Slot" which is only ever used as a boolean (i.e. it's tested against null) - there's no use made of the string value of this property.
3. There are three tests of AzureOptions.Slot against null in PersistAsync, but I think the second two should probably be testing the slot member of the (app,slot) tuple, not the Options member.
4. This is the nasty one - if you get it working with a slot, then when it comes to update the WEBSITE_LOAD_CERTIFICATES configuration item, it will do it in the main app, not the slot (which was our production app, whoops...)

I would like to propose the following functional changes:
1. Make the 'find all the apps for the domain' code at the top of PersistAsync search all the apps and any deployment slots.  To me, this is what one would expect to happen.
2. Fix the WEBSITE_LOAD_CERTIFICATES updating code so that if you're working on a slot, it's the slot which gets updated, not its 'base' app.
3. Mark the 'Slot' property of AzureOptions as obsolete (or remove it, or change it into something with clearer functionality if that's needed)

In addition, I think the following refactoring would be worthwhile and would make the Azure code easier to maintain:
1. Split PersistAsync in to a number of methods which have clearer responsibilities - it's a very large method at the moment which is doing a whole pile of separate things.  This could be a very simple Resharper "Extract Method" sort of refactoring.
2. Move from the (app,slot) tuple to a full custom class, which can provide accessors for some of the base-types which are common to both app and slot - this would facilitate:
3. Some bits of code which are currently doubled into 'slot' and 'non-slot' clauses may be able to share more code than they do.

Would you be interested in a PR to do some/all of this?

**Comment by ffMathy** [comment]
That sounds awesome! 👍👌

**Comment by willdean** [comment]
Fixed in #78
