### ISSUE TITLE
Azure support without needing to load X509 certs

### ISSUE THREAD

**Issue by willdean** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#79]
(Sorry for the Azure noise, here, please feel free to ignore me)

The current Azure implementation needs a rather clever workaround for an issue where the Azure API no longer returns the raw bytes of an X509 certificate.   #12 implemented this work around, which involves first getting the Azure certificate , and then using the Windows certificate store to get the full X509 certificate.  

There are a couple of difficult things about using this technique:
* It's Windows only (maybe that doesn't matter, and the Linux equivalent wouldn't be hard to implement)
* I think it would need a very slightly different implementation on an "Isolated" Azure App Service. (This wouldn't be hard either)
* It involves modifying an app setting to permit the Windows certificate store to load the certificate (this setting is a list of permitted thumbprints).  This has the negative side effect of causing the application to restart whenever the settings are written, and also it's difficult to manage this setting properly, because it can end up being a mixture of manually added thumbprints (for other certs which the app is using) and automatically added ones (for LetsEncrypt).  It's hard for the library to know what's actually needed in that string, and the current code somewhat dodges the issue by just appending new certificate thumbprints to the end, but never removing any.  Eventually this would need to be done manually.

Taking a step back, there isn't actually an absolute requirement for an Azure system to have access to this raw certificate data - the only thing it needs to be able to do is to check if the certificate is still valid, and for that it needs only metadata (issue date, expiry date) which *is* available from the Azure API.   It never needs to obtain the full X509 data.

The challenge to getting away from loading the X509 cert is that the current persistence provider mechanism is based on persisting byte arrays, and it's implicit for a site certificate that this byte array will be the representation of an X509 certificate.

If, instead of persisting a byte array, we persisted some sort of `IAbstractCertificate` which could be 
implemented by both a real X509 certificate and an Azure certificate, then the certificate validator could work without ever needing to retrieve the full certificate.

I have done this here - it's not terribly complicated (and it simplifies the Azure code a lot), but it does touch a lot of code, so it would be a hell of a PR to review and I'm not going to post that unless there's an appetite.    

Maybe @killswtch would have an opinion, as this is chiefly aimed at removing a bunch of his code :-)

**Comment by ffMathy** [comment]
Thank you for the detailed work and explanation. Your proposed solution (although big) would definitely be approved, and makes sense!
