### ISSUE TITLE
Custom domain and certificate in Azure

### ISSUE THREAD

**Issue by pmagnussen** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#9]
How do you add a custom domain in Azure along with the certificate? Is there any documentation on that part?

**Comment by killswtch** [comment]
You should follow Microsoft's documentation on this (https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-domain). The Azure persistence strategy will locate any apps with matching custom domains and attempt to order and then bind a certificate to them.
